### ISSUE TITLE
It's not working

### ISSUE THREAD

**Issue by nixaufer** [dotNETCoreX/SpottyBotty#1]
can u help? I'm new and it always says integrity.log issue. I created integrity.log file in this file I have a code but app is now opening. can u help meto deal with it

**Comment by dotNETCoreX** [comment]
Hey, try replace it with this file. [integrity.log](https://github.com/dotNETCoreX/SpottyBotty/files/8190974/integrity.log)
It should fix it. If you will got any other question you can contact me via mail: dotnetcorex@gmail.com
